version: "0.9"
services:
  backend:
    build: ./engine
    container_name: engine_test
    ports:
      - '5000:5000'
  frontend:
    build: ./ui
    container_name: ui_test
    ports:
      - '3000:3000'
    tty: true